Fundamentos.IS4.Loja/Fundamentos.IS4.Loja.Site/Models/CarrinhoViewModel.cs
using  Fundamentos.IS4.Loja.Domain.Models;
using Fundamentos.IS4.Loja.Domain.ViewObjects;
using System.Collections.Generic;

namespace Fundamentos.IS4.Loja.Site.Models
{
    public class CarrinhoViewModel
    {
        public Carrinho Carrinho { get; set; }
        public IEnumerable<Frete> Fretes { get; set; }
    }
}

Fundamentos.IS4.Loja/Fundamentos.IS4.Loja.Site/Controllers/CarrinhoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Fundamentos.IS4.Loja.Domain.Interfaces;
using Fundamentos.IS4.Loja.Site.Models;
using Fundamentos.IS4.Loja.Site.Service;
using System.Threading.Tasks;
using Fundamentos.IS4.Loja.Domain.Extensions;
using Microsoft.AspNetCore.Authentication;
using System.Linq;

namespace Fundamentos.IS4.Loja.Site.Controllers
{
    [Route("carrinho"), Authorize]
    public class CarrinhoController : Controller
    {
        private readonly ICarrinhoService _carrinhoService;
        private readonly ICarrinhoStore _carrinhoStore;
        private readonly IFreteService _freteService;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IProdutoStore _produtoStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CarrinhoController(
            ICarrinhoService carrinhoService,
            ICarrinhoStore carrinhoStore,
            IFreteService freteService,
            IGeoposicaoService geoposicaoService,
            IProdutoStore produtoStore,
            IHttpContextAccessor httpContextAccessor)
        {
            _carrinhoService = carrinhoService;
            _carrinhoStore = carrinhoStore;
            _freteService = freteService;
            _geoposicaoService = geoposicaoService;
            _produtoStore = produtoStore;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);
            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            var fretes = await _freteService.CalcularCarrinho(carrinho, await _geoposicaoService.GeolocalizarUsuario(), at);
            return View(new CarrinhoViewModel()
            {
                Carrinho = carrinho,
                Fretes = fretes
            });
            
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("cupom")]
        public async Task<IActionResult> Cupom(string returnurl, DescontoCarrinhoViewModel model)
        {
            await _carrinhoService.AplicarCupom(model.Cupom, User.Identity.Name);

            if (returnurl.IsPresent())
                return Redirect(returnurl);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("quantidade")]
        public async Task<IActionResult> Quantidade(AtualizarQuantidadeCarrinhoViewModel model)
        {
            await _carrinhoService.AtualizarQuantidadeProduto(User.Identity.Name, model.NomeUnico, model.Quantidade);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("remover")]
        public async Task<IActionResult> Remover(RemoverProdutoCarrinhoViewModel model)
        {
            await _carrinhoService.Remover(model.NomeUnico, User.Identity.Name);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("adicionar")]
        public async Task<IActionResult> Adicionar(AdicionarProdutoCarrinhoViewModel model)
        {
            var produto = await _produtoStore.ObterPorNome(model.NomeUnico);
            await _carrinhoService.AdicionarProduto(User.Identity.Name, produto, 1);

            return RedirectToAction(nameof(HomeController.Index), "Carrinho");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("selecionar-frete")]
        public async Task<IActionResult> SelecionarFrete(string returnurl, [FromForm] SelecionarFreteViewModel model)
        {
            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            await _carrinhoService.SelecionarFrete(User.Identity.Name, model.Modalidade, await _geoposicaoService.GeolocalizarUsuario(), at);

            if (returnurl.IsPresent())
                return Redirect(returnurl);
            return RedirectToAction(nameof(HomeController.Index), "Carrinho");
        }
    }
}

Fundamentos.IS4.Loja/Fundamentos.IS4.Loja.Site/Controllers/CatalogoController.cs
using Microsoft.AspNetCore.Mvc;
using  Fundamentos.IS4.Loja.Domain.Interfaces;
using  Fundamentos.IS4.Loja.Domain.Models;
using Fundamentos.IS4.Loja.Site.Models;
using Fundamentos.IS4.Loja.Site.Service;
using Fundamentos.IS4.Loja.Domain.ViewObjects;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;

namespace Fundamentos.IS4.Loja.Site.Controllers
{
    [Route("catalogo")]
    public class CatalogoController : Controller
    {
        private readonly IProdutoStore _produtoStore;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IFreteService _freteService;
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaStore _categoriaStore;
        private readonly IMarcaStore _marcaStore;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CatalogoController(
            IProdutoStore produtoStore,
            IGeoposicaoService geoposicaoService,
            IFreteService freteService,
            IProdutoService produtoService,
            ICategoriaStore categoriaStore,
            IMarcaStore marcaStore,
            IHttpContextAccessor httpContextAccessor
            )
        {
            _produtoStore = produtoStore;
            _geoposicaoService = geoposicaoService;
            _freteService = freteService;
            _produtoService = produtoService;
            _categoriaStore = categoriaStore;
            _marcaStore = marcaStore;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [Route("{produto}")]
        public async Task<IActionResult> Detalhes(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            var produtosRelacionados = await _produtoStore.ObterPorCategoria(produtoDetails.Categorias.FirstOrDefault());

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            var frete = await _freteService.ObterModalidades(at);

            return View(new ProdutoDetalhesViewModel()
            {
                Produto = produtoDetails,
                ProdutosRelacionados = produtosRelacionados.Where(w => w.NomeUnico != produtoDetails.NomeUnico).Take(6),
                OpcoesFrete = frete,
            });
        }

        private async Task<string> GeolocalizarUsuario()
        {
            var posicaoDoGuerreiro = Request.Cookies["geoposicao"];
            if (posicaoDoGuerreiro == null)
            {
                var localizacaoDoUsuario = await _geoposicaoService.ObterLocalizacaoAtual();
                posicaoDoGuerreiro = localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude;
                Response.Cookies.Append("geoposicao", localizacaoDoUsuario.Latitude + "|" + localizacaoDoUsuario.Longitude);
            }

            return posicaoDoGuerreiro;
        }

        [Route("visualizar/{produto}")]
        public async Task<IActionResult> PreVisualizar(string produto)
        {
            var produtoDetails = await _produtoStore.ObterPorNome(produto);
            return PartialView("Produtos/_Visualizar", produtoDetails);
        }

        [Route("comentar/{produto}")]
        public async Task<IActionResult> Comentar(string produto, [FromForm] Avaliacao avaliacao)
        {
            avaliacao.ProdutoUrl = produto;
            avaliacao.Imagem = "/images/site/default-user.png";
            await _produtoService.Comentar(avaliacao);
            return RedirectToAction("Detalhes", new { produto });
        }


        [Route("marcas/{marca}")]
        public async Task<IActionResult> Marca(string marca, [FromQuery] PesquisarProdutoVo model)
        {
            model.Marca = marca;
            var marcaDetalhes = await _marcaStore.ObterPorNome(marca);

            return View("Produtos/_ListaProdutos", new ProdutosPrincipalViewModel()
            {
                Produtos = await _produtoStore.PesquisarPorMarca(model),
                ImagemCapa = marcaDetalhes?.Imagem,
                Titulo = marcaDetalhes?.Nome,
                SubTitulo = string.Empty,
                Categorias = await _categoriaStore.ObterTodos(),
                Marcas = await _marcaStore.ObterTodos(),
                PesquisaAtual = model,
                Action = "Lista",
                Controller = "Home"
            });
        }
    }
}

Fundamentos.IS4.Loja/Fundamentos.IS4.Loja.Site/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using  Fundamentos.IS4.Loja.Domain.Interfaces;
using  Fundamentos.IS4.Loja.Domain.Models;
using Fundamentos.IS4.Loja.Site.Models;
using Fundamentos.IS4.Loja.Site.Service;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;

namespace Fundamentos.IS4.Loja.Site.Controllers
{
    [Authorize, Route("checkout")]
    public class CheckoutController : Controller
    {
        private readonly IEnderecoStore _enderecoStore;
        private readonly ICarrinhoStore _carrinhoStore;
        private readonly IFreteService _freteService;
        private readonly ICarrinhoService _carrinhoService;
        private readonly IGeoposicaoService _geoposicaoService;
        private readonly IPedidoService _pedidoService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CheckoutController(
            IEnderecoStore enderecoStore,
            ICarrinhoStore carrinhoStore,
            IFreteService freteService,
            ICarrinhoService carrinhoService,
            IGeoposicaoService geoposicaoService,
            IPedidoService pedidoService,
            IHttpContextAccessor httpContextAccessor)
        {
            _enderecoStore = enderecoStore;
            _carrinhoStore = carrinhoStore;
            _freteService = freteService;
            _carrinhoService = carrinhoService;
            _geoposicaoService = geoposicaoService;
            _pedidoService = pedidoService;
            _httpContextAccessor = httpContextAccessor;
        }

        [Route("dados-pagamento")]
        public async Task<IActionResult> DadosPagamento()
        {
            var enderecosUsuario = await _enderecoStore.ObterDoUsuario(User.Identity.Name);
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            if (carrinho == null)
            {
                TempData["ERRO"] = "Não há itens no carrinho";
                return RedirectToAction("Index", "Carrinho");
            }
            if (!carrinho.FreteSelecionado())
            {
                TempData["ERRO"] = "Selecione o frete";
                return RedirectToAction("Index");
            }
            var cartao = CartaoCredito.Obter().Generate();
            return View(new CheckoutViewModel()
            {
                EnderecosUsuario = enderecosUsuario,
                Carrinho = carrinho,
                CartaoCredito = cartao
            });
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Route("dados-pagamento")]
        public async Task<IActionResult> DadosPagamento(CheckoutViewModel model)
        {
            model.EnderecosUsuario = await _enderecoStore.ObterDoUsuario(User.Identity.Name);
            model.Carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            if (model.Carrinho == null)
            {
                TempData["ERRO"] = "Não há itens no carrinho";
                return RedirectToAction("Index", "Carrinho");
            }

            if (!model.IsValid())
            {
                model.Erro = "Concorde com os termos";
                return View(model);
            }

            var pedido = model.GerarPedido(model.Carrinho, model.EnderecosUsuario);
            await _pedidoService.SalvarPedido(pedido, User.Identity.Name);
            await _carrinhoService.LimparCarrinho(User.Identity.Name);

            return View("ConfirmarPedido", pedido);
        }

        public async Task<IActionResult> Index()
        {
            var carrinho = await _carrinhoStore.ObterCarrinho(User.Identity.Name);

            var at = await _httpContextAccessor.HttpContext.GetTokenAsync("access_token");
            var fretes = await _freteService.CalcularCarrinho(carrinho, await _geoposicaoService.GeolocalizarUsuario(), at);
            return View(new CheckoutViewModel()
            {
                OpcoesFrete = fretes,
                Carrinho = carrinho,
            });
        }
    }
}

Fundamentos.IS4.Loja/Fundamentos.IS4.Loja.Site/Views/Shared/Components/Carrinho/Default.cshtml
@model  Fundamentos.IS4.Loja.Domain.Models.Carrinho
@{
    ViewData["Title"] = "_Carrinho";
}

<div class="navbar-collapse collapse">
    <div class="nav navbar-nav navbar-right hidden-xs">
        <div class="dropdown  cartMenu ">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-shopping-cart"> </i> <span class="cartRespons"> Carrinho (@Model?.TotalProdutos.ToString("C")) </span> <b class="caret"> </b>
            </a>

            <div class="dropdown-menu col-lg-4 col-xs-12 col-md-4 ">
                <div class="w100 miniCartTable scroll-pane">
                    @if (Model != null && Model.Items.Any())
                    {
                        <table>
                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                    <tr class="miniCartProduct">
                                        <td style="width: 20%" class="miniCartProductThumb">
                                            <div>
                                                <a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico">
                                                    <img src="@item.Imagem" alt="@item.Produto">
                                                </a>
                                            </div>
                                        </td>
                                        <td style="width: 40%">
                                            <div class="miniCartDescription">
                                                <h4><a asp-controller="Catalogo" asp-action="Detalhes" asp-route-produto="@item.NomeUnico"> @item.Produto </a></h4>

                                                <div class="price"><span> @item.Valor.ToString("C") </span></div>
                                            </div>
                                        </td>
                                        <td style="width: 10%" class="miniCartQuantity"><a> X @item.Quantidade </a></td>
                                        <td style="width: 15%" class="miniCartSubtotal"><span> @item.Total.ToString("C") </span></td>
                                        <td style="width: 5%" class="delete">
                                            <form asp-controller="Carrinho" asp-action="Remover">
                                                <input type="hidden" name="NomeUnico" value="@item.NomeUnico" />
                                                <button class="btn btn-sm btn-danger" type="submit"> x </button>
                                            </form>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    }
                    else
                    {
                        <table>
                            <tbody>
                                <tr class="text-center"><td>Carrinho vazio</td></tr>
                            </tbody>
                        </table>
                    }

                </div>
                <!--/.miniCartTable-->
                @if (Model != null && Model.Items.Any())
                {
                    <div class="miniCartFooter text-right">
                        <h3 class="text-right subtotal"> Subtotal: @Model?.TotalProdutos.ToString("C") </h3>
                        <a class="btn btn-sm btn-danger" asp-controller="Carrinho" asp-action="Index">
                            <i class="fa fa-shopping-cart"> </i> CARRINHO
                        </a><a class="btn btn-sm btn-primary" asp-action="Index" asp-controller="Checkout"> CHECKOUT </a>
                    </div>
                    <!--/.miniCartFooter-->
                }
            </div>
            <!--/.dropdown-menu-->
        </div> <!--/.cartMenu-->
    </div>
    <!--/.navbar-nav hidden-xs-->
</div>
<!--/.nav-collapse -->